name: Deploy to PROD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compile Hello.cls into PROD IRIS
        run: |
          echo "Running local IRIS compile..."
          iris session IRIS -U USER "##class(Demo.CompileAll).Run()"