name: Deploy to TEST

on:
  push:
    branches: [test]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Export IRIS code
        run: |
          echo "Pretending to deploy to TEST IRIS..."
          echo "Would upload to localhost IRIS and compile."
