name: Deploy to PROD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Simulate deployment to PROD IRIS
        run: |
          echo "=== START PROD DEPLOY ==="
          echo "Deploying Hello.cls to PROD IRIS"
          echo "This is where you would copy files and compile them."
          echo "=== END PROD DEPLOY ==="
